### ISSUE TITLE
NameError when installing with pip

### ISSUE THREAD

**Issue by piotr-dobrogost** [Lispython/pycurl#2]
```
(atest) Z:\3>pip install pycurl2
Downloading/unpacking pycurl2
  Running setup.py egg_info for package pycurl2
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "Z:\3\atest\build\pycurl2\setup.py", line 41, in <module>
        from setup_helpers import extension_params, ParamsPrinter
      File "setup_helpers.py", line 214, in <module>
        extension_params = get_extension_params()
      File "setup_helpers.py", line 87, in get_extension_params
        return make_windows_params(params)
      File "setup_helpers.py", line 165, in make_windows_params
        if not options.curl_dir:
    NameError: global name 'options' is not defined
    Complete output from command python setup.py egg_info:
    <copy of the above traceback>
----------------------------------------
Command python setup.py egg_info failed with error code 1 in Z:\3\atest\build\pycurl2
Storing complete log in C:\Users\Piotr\pip\pip.log
```

**Comment by tarzanjw** [comment]
I got this error, too. Windows 8.

**Comment by nilay** [comment]
I'm not able to install it on Windows 7 using pip and easy_install. Is there any other alternate?

**Comment by piotr-dobrogost** [comment]
@Lispython 
What is needed for this issue to be noticed?

**Comment by Lispython** [comment]
Please, check installation from source that revision.

https://github.com/Lispython/pycurl/commit/2ad51bc1f7f97f11adcff550dc42482012cb1286

I don't have any windows to check work.

**Comment by vlgusev** [comment]
Checked.
You have a typo in 'inculde_dirs' at line 174.

Next problem:
c:\Python27\python.exe setup.py --curl-dir=c:\curl install
Using curl directory: 'c:\curl'usage: setup.py [global_opts] cmd1 [cmd1_opts] [c
md2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: option --curl-dir not recognized

Not sure where to fix it.

And you also get the following behavior:
python.exe setup.py --help
You need specify --curl-dir argument
